version: "3"
services:
  elasticsearch:
    image: elasticsearch:5-alpine
    networks:
      - app_net
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    restart: always
    environment:
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
  node:
    image: node:lts-alpine
    networks:
      - app_net
    ports:
      - ${NODE_PORT}:3000
    restart: always
    user: node
    environment:
      - NODE_ENV=production
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ${FILE_LIST}:/home/node/app/list.txt:ro
    command: "npm start"
networks:
  app_net:
