services:

  elasticsearch:
    image: elasticsearch:8.14.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      http.cors.enabled: true
      http.cors.allow-origin: /.*/
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  elasticsearch:
