version: "3"

services:
  elasticsearch:
    image: elasticsearch:5-alpine
    restart: unless-stopped
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      search_net:

  node:
    image: ghcr.io/soruly/search:latest
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    ports:
      - "${PORT}:3000"
    networks:
      search_net:

networks:
  search_net:
